---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull Roundcube container
  docker_container:
    name: roundcube
    image: roundcube/roundcubemail
    ports:
      - "8080:80"
    state: started
